-- 공급사 정보
CREATE TABLE `SUPPLIER_LIST` (
  `SEQ` int NOT NULL AUTO_INCREMENT COMMENT '고유 식별자',
  `COMPANY_NAME` varchar(100) NOT NULL COMMENT '공급사 이름',
  `SUPPLIER_ID` varchar(100) NOT NULL COMMENT '공급사 ID',
  `SUPPLIER_PW` varchar(100) NOT NULL COMMENT '공급사 PW',
  `SUPPLIER_URL` varchar(255) DEFAULT NULL COMMENT '공급사 URL',
  `MANAGER` varchar(100) DEFAULT NULL COMMENT '담당자 이름',
  `MANAGER_RANK` varchar(50) DEFAULT NULL COMMENT '담당자 직책',
  `NUMBER` varchar(50) DEFAULT NULL COMMENT '담당자 연락처',
  `EMAIL` varchar(255) DEFAULT NULL COMMENT '이메일',
  `STATE_CODE` VARCHAR(4) DEFAULT NULL COMMENT '상태 코드',
  `CREAT_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
  `UPDT_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공급사 목록 테이블';