-- 공급사 정보
CREATE TABLE `SUPPLIER_LIST` (
  `SEQ` int NOT NULL AUTO_INCREMENT COMMENT '고유 식별자',
  `COMPANY_NAME` varchar(100) NOT NULL COMMENT '공급사 이름',
  `SUPPLIER_CODE` varchar(50) DEFAULT NULL COMMENT 'CAFE24 공급사 코드',
  `SUPPLIER_ID` varchar(100) DEFAULT NULL COMMENT '공급사 ID',
  `SUPPLIER_PW` varchar(100) DEFAULT NULL COMMENT '공급사 PW',
  `SUPPLIER_URL` varchar(255) DEFAULT NULL COMMENT '공급사 URL',
  `MANAGER` varchar(100) DEFAULT NULL COMMENT '담당자 이름',
  `MANAGER_RANK` varchar(50) DEFAULT NULL COMMENT '담당자 직책',
  `NUMBER` varchar(50) DEFAULT NULL COMMENT '담당자 연락처',
  `EMAIL` varchar(255) DEFAULT NULL COMMENT '이메일',
  `STATE_CODE` VARCHAR(4) DEFAULT NULL COMMENT '상태 코드',
  `CHANNEL_ID` VARCHAR(30) DEFAULT NULL COMMENT '채널 ID',
  `CONTRACT_STATUS` VARCHAR(20) DEFAULT NULL COMMENT '계약서 상태',
  `CONTRACT_ID` VARCHAR(100) DEFAULT NULL COMMENT '계약서 ID',
  `CREAT_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
  `UPDT_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  PRIMARY KEY (`SEQ`),
  UNIQUE KEY uq_supplier_code (`SUPPLIER_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공급사 목록 테이블';

-- SupplierList 테이블 확장 예시 (DDL)
ALTER TABLE SUPPLIER_LIST
  ADD COLUMN CONTRACT_TEMPLATE VARCHAR(20) NULL COMMENT 'A(단일%)|B(구간%)',
  ADD COLUMN CONTRACT_PERCENT DECIMAL(5,2) NULL COMMENT 'A용: 단일 수수료(%)',
  ADD COLUMN CONTRACT_THRESHOLD BIGINT NULL COMMENT 'B용: 특정 금액(원)',
  ADD COLUMN CONTRACT_PERCENT_UNDER DECIMAL(5,2) NULL COMMENT 'B용: 초과 시 %',
  ADD COLUMN CONTRACT_PERCENT_OVER DECIMAL(5,2) NULL COMMENT 'B용: 이하 시 %',
  ADD COLUMN CONTRACT_SKIP TINYINT(1) DEFAULT 0 COMMENT '외부에서 이미 체결(발송 스킵)';
ALTER TABLE SUPPLIER_LIST
  ADD COLUMN SETTLEMENT_PERIOD VARCHAR(10) NULL COMMENT '정산주기(D/W/M)';

-- Cafe24 웹훅 이벤트 저장 테이블
CREATE TABLE IF NOT EXISTS webhook_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dedupe_key VARCHAR(128) NOT NULL,         -- webhook_id 없을 때 대비(헤더/바디 해시)
  webhook_id VARCHAR(64) NULL,
  topic VARCHAR(128) NULL,
  sig_verified TINYINT(1) NOT NULL DEFAULT 0,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body_json LONGTEXT NULL,
  INDEX idx_topic_received_at (topic, received_at),
  UNIQUE KEY uq_dedupe (dedupe_key)
);

-- OAuth 토큰 저장 테이블 (프로바이더별 1행)
CREATE TABLE IF NOT EXISTS OAUTH_TOKEN (
  PROVIDER      VARCHAR(20)  NOT NULL,               -- 예: 'cafe24'
  MALL_ID       VARCHAR(50)  NULL,                   -- abc123 (선택)
  REFRESH_TOKEN TEXT         NOT NULL,               -- 최신 refresh_token
  ACCESS_TOKEN  TEXT         NULL,                   -- 최근 발급 access_token (선택)
  EXPIRES_AT    DATETIME     NULL,                   -- access_token 만료 시각(선택)
  SCOPE         VARCHAR(255) NULL,                   -- 권한 스코프(선택)
  UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SUPPLIER_DETAIL
CREATE TABLE IF NOT EXISTS SUPPLIER_DETAIL (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  SUPPLIER_SEQ      INT NOT NULL,
  BUSINESS_TYPE     VARCHAR(30) NULL,
  COMPANY_NAME      VARCHAR(100) NULL,
  REPRESENTATIVE_NAME VARCHAR(100) NULL,
  BIZ_REG_NO        VARCHAR(20) NULL,
  COMPANY_EMAIL     VARCHAR(255) NULL,
  COMPANY_PHONE     VARCHAR(50) NULL,
  BANK_CODE         VARCHAR(3) NULL,
  ACCOUNT_NUMBER    VARCHAR(64) NULL,
  HOLDER_NAME       VARCHAR(100) NULL,
  CREAT_DATE        DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDT_DATE         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_SUPPLIER_DETAIL_SUPPLIER_LIST
    FOREIGN KEY (SUPPLIER_SEQ) REFERENCES SUPPLIER_LIST(SEQ) ON DELETE CASCADE,
  CONSTRAINT UX_SUPPLIER_DETAIL_SUPPLIER_SEQ UNIQUE (SUPPLIER_SEQ)
);

-- =========================================================
-- 1) 정산 헤더 (효율형 MySQL)
-- =========================================================
CREATE TABLE IF NOT EXISTS `SETTLEMENT` (
  `ID`               BIGINT NOT NULL AUTO_INCREMENT,

  -- 식별/연결
  `SUPPLIER_SEQ`     INT NOT NULL,                            -- FK → SUPPLIER_LIST.SEQ
  `SUPPLIER_CODE`    VARCHAR(50) NOT NULL,                    -- Cafe24 supplier_code

  -- 기간/주기
  `PERIOD_TYPE`      ENUM('M','W','D') NOT NULL,              -- 월/주/일
  `PERIOD_START`     DATE NOT NULL,
  `PERIOD_END`       DATE NOT NULL,
  `MONTH`            CHAR(7) DEFAULT NULL,                    -- 'YYYY-MM' (필터 편의)

  -- 금액 지표 (원 단위 정수 사용: BIGINT)
  `GROSS_AMOUNT`     BIGINT NOT NULL DEFAULT 0,               -- 총 상품 결제 금액(취소 제외)
  `SHIPPING_AMOUNT`  BIGINT NOT NULL DEFAULT 0,               -- 배송비 합계
  `COMMISSION_RATE`  DECIMAL(5,2) NOT NULL DEFAULT 0.00,      -- 예: 15.00 => 15%
  `COMMISSION_AMOUNT` BIGINT NOT NULL DEFAULT 0,              -- 수수료
  `FINAL_AMOUNT`     BIGINT NOT NULL DEFAULT 0,               -- (GROSS - COMMISSION) + SHIPPING

  -- 상태/전송/정산 흐름
  `STATUS`           ENUM('READY','SENT','CONFIRMED','PAID','RECONCILED','CANCELED')
                     NOT NULL DEFAULT 'READY',
  `DEPOSIT_DUE_DT`   DATE DEFAULT NULL,                       -- 입금 예정일(스냅샷)
  `SENT_AT`          DATETIME DEFAULT NULL,                   -- 슬랙 전송 시각
  `SLACK_CHANNEL_ID` VARCHAR(30) DEFAULT NULL,                -- 채널 ID
  `SLACK_FILE_TS`    VARCHAR(50) DEFAULT NULL,                -- 업로드 ts 등
  `EXCEL_FILE_PATH`  VARCHAR(255) DEFAULT NULL,               -- 생성 파일 경로

  `CREATED_AT`       DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT`       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  UNIQUE KEY `uq_supplier_period` (`SUPPLIER_CODE`,`PERIOD_TYPE`,`PERIOD_START`,`PERIOD_END`),
  KEY `IDX_SETTLEMENT_SUPPLIER` (`SUPPLIER_CODE`,`PERIOD_TYPE`,`PERIOD_START`,`PERIOD_END`),
  KEY `IDX_SETTLEMENT_MONTH` (`MONTH`),

  CONSTRAINT `fk_settlement_supplier`
    FOREIGN KEY (`SUPPLIER_SEQ`) REFERENCES `SUPPLIER_LIST`(`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- =========================================================
-- 2) 정산 상세 (효율형 MySQL)
-- =========================================================
CREATE TABLE IF NOT EXISTS `SETTLEMENT_DETAIL` (
  `ID`                 BIGINT NOT NULL AUTO_INCREMENT,
  `SETTLEMENT_ID`      BIGINT NOT NULL,                   -- FK → SETTLEMENT.ID

  -- 그룹/식별
  `SUPPLIER_CODE`      VARCHAR(50) NOT NULL,              -- 공급사코드
  `ORDER_ID`           VARCHAR(100) DEFAULT NULL,         -- 주문 식별
  `STATUS_LABEL`       ENUM('배송완료','취소처리') NOT NULL,

  -- 엑셀 컬럼(핵심) - TEXT 최소화
  `ORDER_DATE`         DATETIME DEFAULT NULL,             -- 주문일시
  `STORE_NAME`         VARCHAR(100) DEFAULT NULL,         -- 쇼핑몰명
  `BUYER_NAME`         VARCHAR(100) DEFAULT NULL,         -- 주문자명
  `RECEIVER_NAME`      VARCHAR(100) DEFAULT NULL,         -- 수령인
  `RECEIVER_ADDR_FULL` VARCHAR(255) DEFAULT NULL,         -- 주소(255로 제한; 더 길면 500로 상향)
  `RECEIVER_PHONE`     VARCHAR(30) DEFAULT NULL,          -- 전화
  `PRODUCT_NAME`       VARCHAR(200) DEFAULT NULL,         -- 상품명
  `QTY`                INT NOT NULL DEFAULT 0,            -- 수량
  `ITEM_AMOUNT`        BIGINT NOT NULL DEFAULT 0,         -- 상품구매금액(품목)
  `CARRIER_NAME`       VARCHAR(80) DEFAULT NULL,          -- 배송업체
  `TRACKING_NO`        VARCHAR(80) DEFAULT NULL,          -- 운송장번호
  `ORDER_SHIPPING_FEE` BIGINT NOT NULL DEFAULT 0,         -- 배송비(주문단위 표시)

  `CREATED_AT`         DATETIME DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IDX_DETAIL_SETTLEMENT` (`SETTLEMENT_ID`),
  KEY `IDX_DETAIL_SUPPLIER` (`SUPPLIER_CODE`,`STATUS_LABEL`),
  KEY `IDX_DETAIL_ORDER` (`ORDER_ID`),

  CONSTRAINT `fk_detail_header`
    FOREIGN KEY (`SETTLEMENT_ID`) REFERENCES `SETTLEMENT`(`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
